### ISSUE TITLE
Overly strict pinning of `sktime`?

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/autogluon.timeseries-feedstock#10]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
error    libmamba Could not solve for environment specs
    ================== Experimental satisfiability error messages ==================
    You are seeing this because you set `experimental_sat_error_message: true`
    Use the following issue to share feedback on this experimental feature
       https://github.com/mamba-org/mamba/issues/2078
    
    ====================================== Legacy messages (old) =======================================
    Encountered problems while solving:
      - package autogluon-0.7.0-pyhd8ed1ab_0 requires autogluon.timeseries 0.7.0, but none of the providers can be installed
    
    The environment can't be solved, aborting the operation
    =================================== Experimental messages (new) ====================================
    The following packages are incompatible
    └─ autogluon * * is uninstallable because there are no viable options
       ├─ autogluon 0.7.0 would require
       │  └─ autogluon .timeseries 0.7.0, which requires
       │     └─ sktime >=0.14,<0.16 * but there are no viable options
       │        ├─ sktime [0.14.0|0.14.1|0.15.1] would require
       │        │  └─ python >=3.8,<3.9.0a0 *, which conflicts with any installable versions previously reported;
       │        └─ sktime [0.14.0|0.14.1|0.15.1] would require
       │           └─ python >=3.9,<3.10.0a0 *, which conflicts with any installable versions previously reported;
       └─ autogluon 0.6.2 would require
          └─ python >=3.7,<3.10 *, which conflicts with any installable versions previously reported.
    ====================================================================================================
    
critical libmamba Could not solve for environment specs
```

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by dhirschfeld** [comment]
The question is, does `autogluon.timeseries` really not work with `sktime>=0.16` or is this just a defensive pin that hasn't (yet) been updated?

**Comment by giswqs** [comment]
@dhirschfeld I recalled that autogluon had issues with `sktim>=0.16`. See https://github.com/autogluon/autogluon/issues/1242#issuecomment-1424875802. @Innixma might have more information. 

The `autogluon.timeseires` pip dependencies have `sktime>=0.14,<0.16`
https://github.com/autogluon/autogluon/blob/master/timeseries/setup.py#L52

**Comment by dhirschfeld** [comment]
Thanks for the context @giswqs! Looking at the blame there I found:

> *As of v0.7, we are deprecating sktime in AG-TS, due to instability and efficiency issues. Nevertheless, we update the version ranges for conda compatibility. There are no regressions or additional faults in regression tests with v0.14 or v0.15, we cap at 0.16 as we will deprecate in the next release.*

https://github.com/autogluon/autogluon/pull/2877#issue-1578405223

The issue for me is that only `sktime>=0.16` is compatible with `python=3.10`. By pinning `sktime` in `autogluon` it prevents me from installing `sktime` in the same environment as `autogluon`.

It's one thing if `autogluon` will break with `sktime>=0.16` but if that's not the case then I don't think `autogluon` should prevent people from using (compatible versions of) `sktime` alongside it... if they so wish.

**Comment by Innixma** [comment]
I suspect that @canerturkmen chose `<0.16` since `0.16` had just recently released and was not tested with AG for stability.

Worst-case, we remove sktime entirely in `0.7.1` release. Otherwise, if this is a major problem, we can try editing the conda dependencies to include sktime 0.16, although I suspect that would be overkill if this is only a problem when a user wants both autogluon and sktime installed on python 3.10 at the same time. (If you want that, consider using `pip` in the meantime, I think it should work)

**Comment by dhirschfeld** [comment]
> Otherwise, if this is a major problem

I'm fine with it as is, as I'm ok just removing `sktime` from my env - it's not required and by the time 0.7.1 comes around it won't be an issue. Eventual consistency :D
